### ISSUE TITLE
macos | compatibility

### ISSUE THREAD

**Issue by s-ahuja** [krassowski/jupyter-helpers#2]
I tried on macos jupyter...the sound thing didnt work. can you check? i can be a beta tester in that case..

![image](https://user-images.githubusercontent.com/42602606/60019814-5f5d4480-96ac-11e9-865f-6c0a06d16db6.png)

**Comment by krassowski** [comment]
Are there any errors in the Javascript console? Not sure which browser you use, in many browsers, it will open after pressing "F12".

**Comment by s-ahuja** [comment]
worked :). My browser's default wasn't set to "Autoplay" - a feature in most browsers to not start playing videos automatically. However the exception - starting giving 2 beep sounds.
